// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyOrange.DbServices;

namespace MyOrange.DbServices.Migrations
{
    [DbContext(typeof(MyOrangeContext))]
    [Migration("20200423121811_AddSampleDocuments")]
    partial class AddSampleDocuments
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MyOrange.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Email")
                        .HasColumnType("varchar(250)")
                        .HasMaxLength(250)
                        .IsUnicode(false);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("MyOrange.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CONVERT(date, GETDATE())");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedOn")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Documents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Letitia Purdy",
                            CreatedOn = new DateTime(2019, 8, 27, 19, 46, 3, 152, DateTimeKind.Local).AddTicks(472),
                            Description = "Et ex rerum aut rerum doloremque dolore voluptatem.",
                            DocumentType = "Pdf",
                            Size = 9899L,
                            Title = "granite.cif",
                            UpdatedOn = new DateTime(2020, 4, 23, 5, 31, 2, 72, DateTimeKind.Local).AddTicks(2369)
                        },
                        new
                        {
                            Id = 2,
                            Author = "Hosea Padberg",
                            CreatedOn = new DateTime(2019, 8, 14, 13, 38, 29, 225, DateTimeKind.Local).AddTicks(2967),
                            Description = "Iste porro cumque perferendis doloribus aut vero veritatis sint cupiditate.",
                            DocumentType = "CSV",
                            Size = 2801L,
                            Title = "security_fantastic_soft_mouse_virtual.bmp",
                            UpdatedOn = new DateTime(2020, 4, 23, 3, 1, 26, 304, DateTimeKind.Local).AddTicks(1086)
                        },
                        new
                        {
                            Id = 3,
                            Author = "Dakota Bradtke",
                            CreatedOn = new DateTime(2019, 6, 7, 23, 5, 11, 638, DateTimeKind.Local).AddTicks(4751),
                            Description = "Dicta aut corrupti rerum quae quia numquam dicta enim unde.",
                            DocumentType = "CSV",
                            Size = 3134L,
                            Title = "bedfordshire_back_end_incredible_metal_shirt.fcdt",
                            UpdatedOn = new DateTime(2020, 4, 22, 17, 11, 43, 16, DateTimeKind.Local).AddTicks(2345)
                        },
                        new
                        {
                            Id = 4,
                            Author = "Omari Borer",
                            CreatedOn = new DateTime(2019, 6, 22, 7, 38, 36, 755, DateTimeKind.Local).AddTicks(6527),
                            Description = "Rerum quia quos voluptatem veritatis totam ea iure quis.",
                            DocumentType = "Pdf",
                            Size = 175L,
                            Title = "ville.rpss",
                            UpdatedOn = new DateTime(2020, 4, 22, 15, 44, 51, 323, DateTimeKind.Local).AddTicks(1549)
                        },
                        new
                        {
                            Id = 5,
                            Author = "Dexter Kessler",
                            CreatedOn = new DateTime(2020, 3, 29, 10, 49, 17, 672, DateTimeKind.Local).AddTicks(3567),
                            Description = "Ullam quia consequuntur quis voluptatum consequatur.",
                            DocumentType = "Word",
                            Size = 5618L,
                            Title = "ssl.conf",
                            UpdatedOn = new DateTime(2020, 4, 23, 8, 16, 49, 716, DateTimeKind.Local).AddTicks(7448)
                        },
                        new
                        {
                            Id = 6,
                            Author = "Bobbie Stamm",
                            CreatedOn = new DateTime(2019, 6, 26, 11, 41, 34, 794, DateTimeKind.Local).AddTicks(9351),
                            Description = "Ut est neque sit voluptatem magni architecto nostrum sed vitae.",
                            DocumentType = "Word",
                            Size = 9267L,
                            Title = "rustic_fresh_chips_website_invoice.z5",
                            UpdatedOn = new DateTime(2020, 4, 22, 12, 24, 6, 723, DateTimeKind.Local).AddTicks(1637)
                        },
                        new
                        {
                            Id = 7,
                            Author = "Fay Leuschke",
                            CreatedOn = new DateTime(2019, 8, 17, 14, 2, 49, 806, DateTimeKind.Local).AddTicks(9722),
                            Description = "Quidem labore doloremque similique et modi dolorum animi.",
                            DocumentType = "Pdf",
                            Size = 1889L,
                            Title = "senior_concept_microchip.buffer",
                            UpdatedOn = new DateTime(2020, 4, 23, 4, 46, 27, 194, DateTimeKind.Local).AddTicks(7485)
                        },
                        new
                        {
                            Id = 8,
                            Author = "Geoffrey Ritchie",
                            CreatedOn = new DateTime(2019, 7, 28, 0, 10, 47, 459, DateTimeKind.Local).AddTicks(7011),
                            Description = "Dolorem cumque enim at officiis.",
                            DocumentType = "Word",
                            Size = 4774L,
                            Title = "facilitator.m4p",
                            UpdatedOn = new DateTime(2020, 4, 22, 17, 5, 36, 202, DateTimeKind.Local).AddTicks(9356)
                        },
                        new
                        {
                            Id = 9,
                            Author = "Deshawn Wuckert",
                            CreatedOn = new DateTime(2019, 8, 16, 17, 53, 37, 441, DateTimeKind.Local).AddTicks(6938),
                            Description = "Eos corporis officiis facilis velit odio provident nisi autem aut.",
                            DocumentType = "Word",
                            Size = 3313L,
                            Title = "barbados_24_365_lead.mid",
                            UpdatedOn = new DateTime(2020, 4, 22, 16, 32, 48, 96, DateTimeKind.Local).AddTicks(409)
                        },
                        new
                        {
                            Id = 10,
                            Author = "Joyce Simonis",
                            CreatedOn = new DateTime(2020, 3, 18, 10, 41, 54, 389, DateTimeKind.Local).AddTicks(7872),
                            Description = "Atque qui eius odio temporibus quia ut aut voluptatem minima.",
                            DocumentType = "Excel",
                            Size = 9501L,
                            Title = "orchestrate.sig",
                            UpdatedOn = new DateTime(2020, 4, 23, 0, 25, 39, 618, DateTimeKind.Local).AddTicks(1683)
                        },
                        new
                        {
                            Id = 11,
                            Author = "Jaylon O'Hara",
                            CreatedOn = new DateTime(2020, 4, 20, 0, 57, 22, 786, DateTimeKind.Local).AddTicks(7988),
                            Description = "Aut nobis qui ea veritatis excepturi.",
                            DocumentType = "Pdf",
                            Size = 8897L,
                            Title = "lights_factors_cultivate.mods",
                            UpdatedOn = new DateTime(2020, 4, 23, 3, 12, 45, 139, DateTimeKind.Local).AddTicks(7308)
                        },
                        new
                        {
                            Id = 12,
                            Author = "Tressie Reichel",
                            CreatedOn = new DateTime(2020, 2, 28, 13, 31, 36, 284, DateTimeKind.Local).AddTicks(2993),
                            Description = "Tempora animi autem dolor officia.",
                            DocumentType = "Pdf",
                            Size = 3351L,
                            Title = "money_market_account.xpw",
                            UpdatedOn = new DateTime(2020, 4, 22, 20, 32, 53, 454, DateTimeKind.Local).AddTicks(5524)
                        },
                        new
                        {
                            Id = 13,
                            Author = "Jovanny Borer",
                            CreatedOn = new DateTime(2019, 7, 16, 17, 59, 54, 903, DateTimeKind.Local).AddTicks(8878),
                            Description = "Cum corrupti esse.",
                            DocumentType = "Excel",
                            Size = 6552L,
                            Title = "outdoors.acc",
                            UpdatedOn = new DateTime(2020, 4, 23, 10, 50, 19, 210, DateTimeKind.Local).AddTicks(3826)
                        },
                        new
                        {
                            Id = 14,
                            Author = "Jany Abernathy",
                            CreatedOn = new DateTime(2019, 9, 26, 13, 56, 33, 86, DateTimeKind.Local).AddTicks(5839),
                            Description = "Laborum dolores quia soluta ut cupiditate ex dicta.",
                            DocumentType = "Word",
                            Size = 2170L,
                            Title = "intelligent_granite_bacon.swi",
                            UpdatedOn = new DateTime(2020, 4, 23, 8, 14, 9, 794, DateTimeKind.Local).AddTicks(6261)
                        },
                        new
                        {
                            Id = 15,
                            Author = "Jolie Huels",
                            CreatedOn = new DateTime(2020, 3, 12, 21, 30, 48, 672, DateTimeKind.Local).AddTicks(1929),
                            Description = "Omnis aut soluta qui eum ipsam expedita dolores non eligendi.",
                            DocumentType = "Excel",
                            Size = 9737L,
                            Title = "meadow.iota",
                            UpdatedOn = new DateTime(2020, 4, 22, 23, 10, 34, 81, DateTimeKind.Local).AddTicks(6975)
                        },
                        new
                        {
                            Id = 16,
                            Author = "Yvonne Kunde",
                            CreatedOn = new DateTime(2019, 7, 19, 12, 4, 55, 336, DateTimeKind.Local).AddTicks(8888),
                            Description = "Adipisci necessitatibus ab dicta vero blanditiis est nostrum.",
                            DocumentType = "Word",
                            Size = 8822L,
                            Title = "manors_back_end_plastic.plf",
                            UpdatedOn = new DateTime(2020, 4, 22, 13, 59, 32, 762, DateTimeKind.Local).AddTicks(1131)
                        },
                        new
                        {
                            Id = 17,
                            Author = "Lonzo Jones",
                            CreatedOn = new DateTime(2020, 1, 26, 20, 18, 28, 297, DateTimeKind.Local).AddTicks(8980),
                            Description = "Sapiente est enim consequatur consequatur autem temporibus.",
                            DocumentType = "Pdf",
                            Size = 6477L,
                            Title = "burg_fantastic_concrete_bike.rmvb",
                            UpdatedOn = new DateTime(2020, 4, 23, 1, 14, 46, 855, DateTimeKind.Local).AddTicks(4291)
                        },
                        new
                        {
                            Id = 18,
                            Author = "Wyatt Watsica",
                            CreatedOn = new DateTime(2020, 2, 3, 22, 50, 32, 961, DateTimeKind.Local).AddTicks(5212),
                            Description = "Voluptatem placeat laudantium repellat.",
                            DocumentType = "Excel",
                            Size = 937L,
                            Title = "action_items_face_to_face.fly",
                            UpdatedOn = new DateTime(2020, 4, 23, 9, 15, 36, 959, DateTimeKind.Local).AddTicks(3335)
                        },
                        new
                        {
                            Id = 19,
                            Author = "Cordie Pollich",
                            CreatedOn = new DateTime(2020, 3, 20, 21, 30, 37, 860, DateTimeKind.Local).AddTicks(5527),
                            Description = "Voluptatum officia qui.",
                            DocumentType = "CSV",
                            Size = 6857L,
                            Title = "buckinghamshire.gim",
                            UpdatedOn = new DateTime(2020, 4, 22, 18, 14, 34, 567, DateTimeKind.Local).AddTicks(9668)
                        },
                        new
                        {
                            Id = 20,
                            Author = "Sigrid Cronin",
                            CreatedOn = new DateTime(2020, 1, 14, 3, 30, 16, 902, DateTimeKind.Local).AddTicks(722),
                            Description = "Hic ipsam tempora rem.",
                            DocumentType = "Excel",
                            Size = 2179L,
                            Title = "xss_orchestrator.tiff",
                            UpdatedOn = new DateTime(2020, 4, 22, 14, 13, 51, 32, DateTimeKind.Local).AddTicks(4175)
                        });
                });

            modelBuilder.Entity("MyOrange.Models.DocumentDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("DocumentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("DocumentDetails");
                });

            modelBuilder.Entity("MyOrange.Models.Document", b =>
                {
                    b.HasOne("MyOrange.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");
                });

            modelBuilder.Entity("MyOrange.Models.DocumentDetail", b =>
                {
                    b.HasOne("MyOrange.Models.Document", null)
                        .WithMany("Details")
                        .HasForeignKey("DocumentId");
                });
#pragma warning restore 612, 618
        }
    }
}
